# K3sAdmin Vars

fs_mounts:
  - {
    path: /mnt/ssd/movies,
    src: "UUID=0CB81103B810ED48",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro",
  }
  - {
    path: /mnt/ssd/series,
    src: "UUID=56885E3A885E18B7",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro",
  }
  - {
    path: /mnt/ssd/pny250,
    src: "UUID=1DAC99F73EFA9CB8",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro",
  }
  - {
    path: /mnt/hdd/tera,
    src: "UUID=D4504CF8504CE33A",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro"
  }
  - {
    path: /mnt/hdd/barracuda,
    src: "UUID=24FEA26DFEA236C8",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro"
  }
  - {
    path: /mnt/ssd/ex2,
    src: "UUID=8e0dfd97-1bfc-40f3-af1c-3bff20d80df9",
    fstype: ext4,
    opts: "defaults,nofail"
  }

nfs_shares:
  - /mnt/ssd/movies *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/ssd/series *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/ssd/pny250 *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/ssd/ex2 *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/hdd/tera *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/hdd/barracuda *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
